name: Build and Test Main
on: [push]
jobs:
  build:
    runs-on: windows
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - run: mvn compile
